### ISSUE TITLE
plugin fails on v18.12 (fbf8ea1)

### ISSUE THREAD

**Issue by sdenaro** [fxneumann/oneclickpocket#11]
oneclickpocket is failing under Tiny Tiny RSS v18.12 (fbf8ea1) with "`Uncaught TypeError: shareArticleToPocket is not a function`" and a stack trace of

`TypeError: shareArticleToPocket is not a function
    at HTMLImageElement.onclick (https://<<MY DOMAIN NAME>>.com/ttrss/index.php#f=-3&c=0:1:1)`

this on Debian 9, nginx, php7, mysql.

reverting to prior ttrss fixes issue. looks like the newer version of tt-rss introduces some js changes that break this plugin.

**Comment by Egorkat** [comment]
same issue here...

**Comment by sdenaro** [comment]
@Egorkat @joshp23  I put a fix here if you wan to try.

https://github.com/sdenaro/oneclickpocket/blob/master/pocket.js

**Comment by fxneumann** [comment]
Thanks for the update! Really appreciated, as I still use the plugin but don't have that many time to maintain it.

**Comment by sdenaro** [comment]
Felix, I am going to work on the two remaining issues with my hack, that the button doesn't update and that the text on the bottom isn't in the theme. Can I email you when I get around to fixing that?

**Comment by Egorkat** [comment]
The fix provided does work for me, many thanks! Even button gets updated - turns it's color after article is pocket'd.

**Comment by sdenaro** [comment]
I'm seeing this before click:

![image](https://user-images.githubusercontent.com/270809/50007213-39791980-ff7e-11e8-8c9f-c62889bcdd56.png)

And this after:

![image](https://user-images.githubusercontent.com/270809/50007254-5ada0580-ff7e-11e8-98fb-e71c7370686c.png)

**Comment by Egorkat** [comment]
For me it looks much better. Theme is night_blue, but was also ok with default theme.
Before:
![before](https://user-images.githubusercontent.com/10372472/50073142-544ac880-01e0-11e9-8778-b5132376635d.png)

After:
![after](https://user-images.githubusercontent.com/10372472/50073153-5c0a6d00-01e0-11e9-8ea7-1a95da81a1e3.png)
