### ISSUE TITLE
Database fields aren't updating with consumer key and auth

### ISSUE THREAD

**Issue by Cam** [fxneumann/oneclickpocket#8]
I'm assuming this project is dead.. but hoping it isn't :)

I can't seem to get my key and auth to save via the admin. I also tried manually adding them to the database, but that doesn't seem to work either.

The error I am getting is "(X-Error: This Consumer Key was not found. You can create a Consumer Key at http:\/\/getpocket.com\/api\/. )"

Any help would be more than appreciated.

**Comment by kepi** [comment]
I suggest to use https://github.com/Arthaey/oneclickpocket which has this one "fixed".
